// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Square$ReactHooksTemplate = require("./Square.bs.js");

function text(prim) {
  return prim;
}

function Board(Props) {
  var match = React.useState((function () {
          return Caml_array.caml_make_vect(9, undefined);
        }));
  var setSquares = match[1];
  var squares = match[0];
  var match$1 = React.useState((function () {
          return "X";
        }));
  var setNextPlayer = match$1[1];
  var nextPlayer = match$1[0];
  var handleClick = function (i) {
    return Curry._1(setSquares, (function (squares) {
                  return $$Array.mapi((function (index, v) {
                                var match = i === index;
                                if (match) {
                                  if (v !== undefined) {
                                    return undefined;
                                  } else {
                                    return nextPlayer;
                                  }
                                } else {
                                  return v;
                                }
                              }), squares);
                }));
  };
  var renderSquare = function (i) {
    var match = Caml_array.caml_array_get(squares, i);
    return React.createElement(Square$ReactHooksTemplate.make, {
                value: match !== undefined ? match : "",
                onClick: (function (param) {
                    handleClick(i);
                    return Curry._1(setNextPlayer, (function (nextPlayer) {
                                  var match = nextPlayer === "X";
                                  if (match) {
                                    return "O";
                                  } else {
                                    return "X";
                                  }
                                }));
                  })
              });
  };
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "status"
                }, "Next player: " + nextPlayer), React.createElement("div", {
                  className: "board-row"
                }, renderSquare(0), renderSquare(1), renderSquare(2)), React.createElement("div", {
                  className: "board-row"
                }, renderSquare(3), renderSquare(4), renderSquare(5)), React.createElement("div", {
                  className: "board-row"
                }, renderSquare(6), renderSquare(7), renderSquare(8)));
}

var make = Board;

exports.text = text;
exports.make = make;
/* react Not a pure module */
