// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Board$ReactHooksTemplate = require("./Board.bs.js");

function text(prim) {
  return prim;
}

function Game(Props) {
  return React.createElement("div", {
              className: "game"
            }, React.createElement("div", {
                  className: "game-board"
                }, React.createElement(Board$ReactHooksTemplate.make, { })), React.createElement("div", {
                  className: "game-info"
                }));
}

var make = Game;

exports.text = text;
exports.make = make;
/* react Not a pure module */
