// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Game$ReactHooksTemplate = require("./Game.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Game$ReactHooksTemplate.make, { }), "app");

/*  Not a pure module */
